### ISSUE TITLE
macos's `trash' need "-F" arguments

### ISSUE THREAD

**Issue by dolmens** [lunaryorn/osx-trash.el#2]
Without "-F", the Finder cannot putback the trashed file.

**Comment by wyuenho** [comment]
Make a PR?

**Comment by tarsius** [comment]
> Without "-F", the Finder cannot putback the trashed file.

What does that mean? Could you maybe link to a manpage or something like that, that documents what this argument does.

@wyuenho the commit message should explain what effect `-F` has and why we want that.

**Comment by wyuenho** [comment]
It means exactly what the description says. Without `-F`, the system doesn't wouldn't record the origin of the file before it went into the Trash directory, so it wouldn't know where to put the file back, so that option becomes unavailable.

```
usage: trash [-vlesyF] <file> [<file> ...]

  Move files/folders to the trash.

  Options to use with <file>:

  -v  Be verbose (show files as they are trashed, or if
      used with the -l option, show additional information
      about the trash contents)
  -F  Ask Finder to move the files to the trash, instead of
      using the system API.

  Stand-alone options (to use without <file>):

  -l  List items currently in the trash (add the -v option
      to see additional information)
  -e  Empty the trash (asks for confirmation)
  -s  Securely empty the trash (asks for confirmation)
  -y  Skips the confirmation prompt for -e and -s.
      CAUTION: Deletes permanently instantly.

  Options supported by `rm` are silently accepted.

Version 0.9.2
Copyright (c) 2010–2018 Ali Rantakari, http://hasseg.org/trash
```

**Comment by tarsius** [comment]
> It means exactly what the description says.

Yes, it is sufficiently clear in context. Better than the official documentation in fact, though in this case that is a very low bar. :grin:

**Comment by tarsius** [comment]
I have added a new option, `osx-trash-command`. If you want to keep using `trash` (with or without a `-F` argument), you now have to set that option explicitly.
