### ISSUE TITLE
Needs new maintainer

### ISSUE THREAD

**Issue by tarsius** [lunaryorn/osx-trash.el#6]
Apparently this package still has users. And also bugs.

I don't use macOS, so I can't really be of much help.

Would you like to maintain this? Shouldn't be to hard if you use macOS.

/cc @yugaego @dolmens @wyuenho

**Comment by wyuenho** [comment]
In Emacs 29 the NS port will have a [system trash](https://github.com/emacs-mirror/emacs/commit/796075ef7e1c7a294fe8c3c36c999c10c2f09d38) implementation, and that one issue in this package is to not rely on osascript. But osascript comes with macOS, so I don't think there's any urgency to deal with it. Besides, I think very few people actually write AppleScript lol.

So basically, what I'm trying to say is, I can be a maintainer, but I mostly likely will not be doing anything to address that issue.
